In [0]:
#Principal Component Analysis

from numpy import array
from sklearn.decomposition import PCA

In [2]:
#define a matrix
A= array([[1,2],[3,4],[5,6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [0]:
#create th pca instance
pca= PCA(2)

In [6]:
#fit on data

pca.fit(A)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [9]:
#access values and vectors

print(pca.components_)
print(pca.explained_variance_)



[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
[8. 0.]


In [12]:
#transform data

B= pca.transform(A)
print(B)

[[-2.82842712e+00 -2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00]
 [ 2.82842712e+00  2.22044605e-16]]
