In [0]:
#importing required libraries

from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig

In [0]:
#define a matrix
A= array([[1,2],[3,4],[5,6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [0]:
#calculate the mean of each column

M= mean(A.T, axis=1)
print(M)

[3. 4.]


In [0]:
#center columns by substracting columns means
C=A-M
print(C)

[[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]


In [0]:
#calculate covariance matrix of centered matrix
V=cov(C.T)
print(V)

[[4. 4.]
 [4. 4.]]


In [0]:
#eigendecomposition of covariance matrix
values,vectors=eig(V)
print(values)
print(vectors)

[8. 0.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [12]:
#project data
P= vectors.T.dot(C.T)
print(P.T)

[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]
